id = "github-yaml"
name = "GitHub YAML (Actions, Workflows, Issues, Discussions, etc)"
version = "0.1.0"
schema_version = 1
authors = ["Peter Tripp <petertripp@gmail.com>"]
description = "GitHub YAML language and schema support (check README.md for instructions)"
repository = "https://github.com/notpeter/github-yaml-zed"

[language_servers.dummy-github-yaml-lsp]
name = "Dummy GitHub YAML LSP"
language = "GitHub Workflow"

[grammars.ghactions]
repository = "https://github.com/rmuir/tree-sitter-ghactions"
commit = "1af70d96c09dbfc1a6eeeef15c4f4373b4d38a79"

[grammars.nim_format_string]
repository = "https://github.com/aMOPel/tree-sitter-nim-format-string"
commit = "d45f75022d147cda056e98bfba68222c9c8eca3a"

[grammars.codeowners]
repository = "https://github.com/lukasmalkmus/tree-sitter-codeowners"
commit = "5fc25f72a44d2fe5b9218c712062dcec79dac87e"
