id = "github-actions-workflows"
name = "GitHub Workflows"
version = "0.0.1"
schema_version = 1
authors = ["Peter Tripp <notpeter@users.noreply.github.com>"]
description = "Language support for GitHub Actions workflow files."
repository = "https://github.com/notpeter/github-actions-workflows-zed"

[grammars.ghactions]
repository = "https://github.com/rmuir/tree-sitter-ghactions"
commit = "1af70d96c09dbfc1a6eeeef15c4f4373b4d38a79"
